cluster_context:
  alb_CertificateArn: ''
  alb_Subnets: ''
  alb_SecurityGroups: ''
  applicationKey: ''
  applicationService: ''
  applicationName: ''
  pipelineBuildNumber: ''
  pipelineBranch: ''
  environment: ''
  environmentRegion: ''
  networkDomainName: ''

http_proxy: ''
no_proxy: ''

ecr:
  registry: ''
  prefix: ''
image: ''
