apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /home/mwhalen18/kompose/komposer-apps/test-app/docker-compose.yml -o /home/mwhalen18/ci-cluster/kubernetes/test-app convert -c
    kompose.service.type: NodePort
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: streamlit
  type: NodePort
