apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f webserver.yaml convert -c
    kompose.service.type: NodePort
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    app: Streamlit-Webserver-App
    io.kompose.service: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f webserver.yaml convert -c
        kompose.service.type: NodePort
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - args:
            - --server.headless=true
            - --server.enableCORS=false
          image: localhost:5000/streamlit-app
          name: streamlit
          ports:
            - containerPort: 8501
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "2147483648"
            requests:
              cpu: 250m
              memory: "20971520"
      restartPolicy: Always
