apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /home/mwhalen18/kompose/komposer-apps/webserver//docker-compose.yml convert -o /home/mwhalen18/ci-cluster/kubernetes/eks-apps/webserver
    kompose.service.type: NodePort
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: webserver
  type: NodePort
