apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f /home/mwhalen18/kompose/komposer-apps/webserver//docker-compose.yml convert -o /home/mwhalen18/ci-cluster/kubernetes/eks-apps/webserver
    kompose.service.type: NodePort
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    app: streamlit-webserver-app
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f /home/mwhalen18/kompose/komposer-apps/webserver//docker-compose.yml convert -o /home/mwhalen18/ci-cluster/kubernetes/eks-apps/webserver
        kompose.service.type: NodePort
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: webserver
    spec:
      containers:
        - args:
            - --server.headless=true
            - --server.enableCORS=false
          image: localhost:5000/streamlit-app:latest
          name: webserver
          ports:
            - containerPort: 8501
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "2147483648"
            requests:
              cpu: 250m
              memory: "20971520"
      restartPolicy: Always
