apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd  # ArgoCD lives here
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: 38.0.2
    helm:
      valueFiles:
        - traefik-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik  # <- where Traefik is installed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
