spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mwhalen18/dev-cluster
    targetRevision: HEAD
    path: kubernetes
  cluster_context:
    alb_CertificateArn: ''
    alb_Subnets: ''
    alb_SecurityGroups: ''
    applicationKey: ''
    applicationService: ''
    applicationName: ''
    pipelineBuildNumber: ''
    pipelineBranch: ''
    environment: ''
    environmentRegion: ''
    networkDomainName: ''
web_apps:
  - name: test-app
    description: Test
    service: streamlit
    port: "4000"
    namespace: test-app
    ad_group: all
    url_base_pathname: /
  - name: webserver
    description: Test
    service: streamlit
    port: "4000"
    namespace: webserver
    ad_group: all
    url_base_pathname: /
test_app:
  image: streamlit-app
webserver:
  image: streamlit-app
